config/routes.rb
Rails.application.routes.draw do
  resources :nii_types
  resources :cinii_books, only: [:index, :create]
end

app/controllers/nii_types_controller.rb
class NiiTypesController < ApplicationController
  before_action :set_nii_type, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]

  # GET /nii_types
  # GET /nii_types.json
  def index
    @nii_types = NiiType.order(:position)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nii_types }
    end
  end

  # GET /nii_types/1
  # GET /nii_types/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nii_type }
    end
  end

  # GET /nii_types/new
  # GET /nii_types/new.json
  def new
    @nii_type = NiiType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nii_type }
    end
  end

  # GET /nii_types/1/edit
  def edit
  end

  # POST /nii_types
  # POST /nii_types.json
  def create
    @nii_type = NiiType.new(nii_type_params)

    respond_to do |format|
      if @nii_type.save
        format.html { redirect_to @nii_type, notice:  t('controller.successfully_created', model:  t('activerecord.models.nii_type')) }
        format.json { render json: @nii_type, status: :created, location: @nii_type }
      else
        format.html { render action: "new" }
        format.json { render json: @nii_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nii_types/1
  # PUT /nii_types/1.json
  def update
    if params[:move]
      move_position(@nii_type, params[:move])
      return
    end

    respond_to do |format|
      if @nii_type.update(nii_type_params)
        format.html { redirect_to @nii_type, notice:  t('controller.successfully_updated', model:  t('activerecord.models.nii_type')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nii_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nii_types/1
  # DELETE /nii_types/1.json
  def destroy
    @nii_type.destroy

    respond_to do |format|
      format.html { redirect_to nii_types_url, notice: t('controller.successfully_deleted', model: t('activerecord.models.nii_type')) }
      format.json { head :no_content }
    end
  end

  private
  def set_nii_type
    @nii_type = NiiType.find(params[:id])
    authorize @nii_type
  end

  def check_policy
    authorize NiiType
  end

  def nii_type_params
    params.require(:nii_type).permit(:name, :display_name, :note)
  end
end

app/helpers/nii_types_helper.rb
module NiiTypesHelper
end

app/views/nii_types/_form.html.erb
<%= form_for(@nii_type) do |f| -%>
  <%= f.error_messages -%>
  <p>
    <%= f.label t('activerecord.attributes.nii_type.name') -%><br />
    <%= f.text_field :name, :class => 'short_name' -%>
  </p>
  <p>
    <%= f.label t('activerecord.attributes.nii_type.display_name') -%><br />
    <%= f.text_area :display_name, :class => 'resource_textarea' -%>
  </p>
  <p>
    <%= f.label t('activerecord.attributes.nii_type.note') -%><br />
    <%= f.text_area :note, :class => 'resource_textarea' -%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%- end -%>

app/views/nii_types/edit.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.editing', :model => t('activerecord.models.nii_type')) -%></h1>
<div id="content_list">
  <%= render 'form' %>
</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.show'), @nii_type -%></li>
    <li><%= link_to t('page.back'), nii_types_path -%></li>
  </ul>
</div>

app/views/nii_types/index.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.nii_type')) -%></h1>
<div id="content_list">

<table class="table table-striped index">
  <tr>
    <th id="position"></th>
    <th><%= t('activerecord.attributes.nii_type.name') -%></th>
    <th><%= t('activerecord.attributes.nii_type.note') -%></th>
    <th></th>
  </tr>

<%- @nii_types.each do |nii_type| -%>
  <tr class="line<%= cycle("0", "1") -%>">
    <td>
      <%- if policy(nii_type).update? -%>
        <%= move_position(nii_type) -%>
      <%- end -%>
    </td>
    <td>
      <%= link_to h(nii_type.display_name.localize), nii_type -%>
      <br />
      (<%= link_to h(nii_type.name), nii_type -%>)
    </td>
    <td><%= nii_type.note -%></td>
    <td>
      <%- if policy(nii_type).update? -%>
        <%= link_to t('page.edit'), edit_nii_type_path(nii_type) -%>
      <% end %>
      <%- if policy(nii_type).destroy? -%>
        <%= link_to t('page.destroy'), nii_type, :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%>
      <% end -%>
    </td>
  </tr>
<%- end -%>
</table>

</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.new', :model => t('activerecord.models.nii_type')), new_nii_type_path -%></li>
  </ul>
</div>

app/views/nii_types/new.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.new', :model => t('activerecord.models.nii_type')) -%></h1>
<div id="content_list">
  <%= render 'form' %>
</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.back'), nii_types_path -%></li>
  </ul>
</div>

app/views/nii_types/show.html.erb
<div id="content_detail" class="ui-corner-all ui-widget-content">
<h1 class="title"><%= t('page.showing', :model => t('activerecord.models.nii_type')) -%></h1>
<div id="content_list">
<p>
  <strong><%= t('activerecord.attributes.nii_type.name') -%>:</strong>
  <%= @nii_type.name -%>
</p>

<p>
  <strong><%= t('activerecord.attributes.nii_type.display_name') -%>:</strong>
  <%= @nii_type.display_name.localize -%>
</p>

<p>
  <strong><%= t('activerecord.attributes.nii_type.note') -%>:</strong>
  <%= @nii_type.note -%>
</p>

</div>
</div>

<div id="submenu" class="ui-corner-all ui-widget-content">
  <ul>
    <li><%= link_to t('page.edit'), edit_nii_type_path(@nii_type) -%></li>
    <li><%= back_to_index -%></li>
  </ul>
</div>